<?php

namespace App\Filament\Project\Resources;

use App\Filament\Project\Clusters\KnowledgeBase;
use App\Filament\Project\Resources\KnowledgeArticleResource\Pages;
use App\Filament\Project\Resources\KnowledgeCategoryResource\Pages\ViewKnowledgeArticle;
use App\Models\KnowledgeArticle;
use Filament\Actions\DeleteAction;
use Filament\Facades\Filament;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Infolists\Infolist;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Mohamedsabil83\FilamentFormsTinyeditor\Components\TinyEditor;

class KnowledgeArticleResource extends Resource
{
    protected static ?string $model = KnowledgeArticle::class;

    protected static ?string $navigationIcon = 'heroicon-o-book-open';

    protected static ?string $label = 'Članak';

    protected static ?string $pluralLabel = 'Članci';

    protected static ?string $cluster = KnowledgeBase::class;

    public static function getNavigationBadge(): ?string
    {
        return Filament::getTenant()->knowledgeArticles()->count();
    }

    public static function infolist(Infolist $infolist): Infolist
    {
        return parent::infolist($infolist); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('title')
                    ->required()
                    ->label('Naslov'),

                Select::make('category_id')
                    ->required()
                    ->native(false)
                    ->relationship('category', 'title')
                    ->label('Kategorija'),

                TinyEditor::make('content')
                    ->label('Sadržaj')
                    ->minHeight(600)
                    ->columnSpanFull()
                    ->required(),

                SpatieMediaLibraryFileUpload::make('attachments')
                    ->collection('knowledge-article')
                    ->multiple()
                    ->downloadable()
                    ->label('Privitci')
                    ->columnSpanFull()

            ])->columns(2);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\ColorColumn::make('category.color')
                    ->label(''),

                Tables\Columns\TextColumn::make('title')
                    ->label('Naziv'),

                Tables\Columns\TextColumn::make('category.title')
                    ->label('Kategorija')
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListKnowledgeArticles::route('/'),
            'view' => ViewKnowledgeArticle::route('/{record}'),

            //'create' => Pages\CreateKnowledgeArticle::route('/create'),
            //'edit' => Pages\EditKnowledgeArticle::route('/{record}/edit'),
        ];
    }
}
